### ISSUE TITLE
RequestFailedException(message: Invalid type for 'messages[1].content[1].image_url': expected an object, but got a string instead., statusCode: 400)

### ISSUE THREAD

**Issue by lukehutch** [anasfik/openai#203]
When trying the chat example, I get:

```
RequestFailedException(message: Invalid type for 'messages[1].content[1].image_url': expected an object, but got a string instead., statusCode: 400)
#0      OpenAINetworkingClient.post (package:dart_openai/src/core/networking/client.dart:332:7)
<asynchronous suspension>
#1      OpenAIChat.create (package:dart_openai/src/instance/chat/chat.dart:87:12)
<asynchronous suspension>
#2      run (package:qa/qa.dart:68:46)
<asynchronous suspension>
#3      main (file:///Users/lhutchison/qa/bin/qa.dart:8:3)
<asynchronous suspension>
```

**Comment by pagebook1** [comment]
Same.. it's because of image_url .  please fix thanks ..

**Comment by pagebook1** [comment]
I fixed it.. try to make a pr. 
i changed the content.dart line 55 from
`  Map<String, dynamic> toMap() {
    return {
      "type": type,
      if (text != null) "text": text,
      if (imageUrl != null) "image_url": imageUrl,
    };
  }`
to
`  Map<String, dynamic> toMap() {
    return {
      "type": type,
      if (text != null) "text": text,
      if (imageUrl != null)
        "image_url": {
          "url": imageUrl,
        },
    };
  }`

**Comment by pagebook1** [comment]
as I see on the latest pr, it's fixed but still not updated on the pub.dev

**Comment by Lucheti** [comment]
any ideas if this is fixed? im on ^5.1.0 and getting the same error

**Comment by pagebook1** [comment]
> any ideas if this is fixed? im on ^5.1.0 and getting the same error
you can just manually change the code bro.

**Comment by anasfik** [comment]
Thank you!

Resolved, please update to latest versions
