### ISSUE TITLE
error use 1.9.0

### ISSUE THREAD

**Issue by badboy-tian** [anasfik/openai#30]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'int' of 'index'
                                                                                                    #0      OpenAINetworkingClient.postStream.<anonymous closure>.<anonymous closure> (package:dart_openai/src/core/networking/client.dart:228:24)
                                                                                                    #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1593:10)
                                                                                                    #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
                                                                                                    #3      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
                                                                                                    #4      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
                                                                                                    #5      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
                                                                                                    #6      _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
                                                                                                    #7      _LineSplitterSink.close (dart:convert/line_splitter.dart:134:13)
                                                                                                    #8      _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
                                                                                                    #9      _RootZone.runGuarded (dart:async/zone.dart:1581:10)
                                                                                                    #10     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
                                                                                                    #11     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
                                                                                                    #12     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                                                                                                    #13     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
                                                                                                    #14     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
                                                                                                    #15     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
                                                                                                    #16     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:305:20)
                                                                                                    #17     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:81:18)
                                                                                                    #18     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
                                                                                                    #19     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
                                                                                                    #20     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
                                                                                                    #21     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
                                                                                                    #22     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                                                                                                    #23     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
                                                                                                    #24     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
                                                                                                    #25     _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:714:15)
                                                                                                    #26     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
                                                                                                    #27     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
                                                                                                    #28     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
                                                                                                    #29     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
                                                                                                    #30     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:99:10)
                                                                                                    #31     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:161:13)
                                                                                                    #32     _RootZone.runGuarded (dart:async/zone.dart:1581:10)
                                                                                                    #33     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
                                                                                                    #34     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
                                                                                                    #35     _DelayedDone.perform (dart:async/stream_impl.dart:534:14)
                                                                                                    #36     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
                                                                                                    #37     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
                                                                                                    #38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
                                                                                                    #39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

```

**Comment by anasfik** [comment]
Thank you for getting here!

can you provide a sample code of the request that you tried to make?
